[scrapyd]
eggs_dir    = /var/lib/scrapyd/eggs
logs_dir    = /var/lib/scrapyd/logs
items_dir   =
dbs_dir     = /var/lib/scrapyd/dbs
jobs_to_keep = 5
max_proc    = 20
max_proc_per_cpu = 20
finished_to_keep = 100
poll_interval = 5.0
bind_address = 0.0.0.0
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
launcher    = scrapyd.launcher.Launcher
webroot     = scrapyd.website.Root
nodename    = %(hostname)s
