[MYSQL]
host = %(SPIDER_MYSQL_HOST_PROD)s
user = %(SPIDER_MYSQL_USER_PROD)s
password = %(SPIDER_MYSQL_PASSWORD_PROD)s
port = 3306
dbname = crawl_data

[REDIS]
;host = %(SPIDER_REDIS_HOST_PROD)s
host = 10.88.0.1
password = %(SPIDER_REDIS_PASSWORD_PROD)s
port = 6379
db = 1

[KAFKA]
host = %(SPIDER_KAFKA_HOST_PROD)s
topic = monitor_news

[LLM]
host = http://%(SPIDER_LLM_HOST_PROD)s/v1/chat/completions
api_key = %(SPIDER_LLM_API_KEY_PROD)s
model = Qwen/Qwen3-1.7B

[NODE]
exec_js_url = http://%(SPIDER_NODE_SERVER_PROD)s/exec_jsc
exec_ts_url = http://%(SPIDER_NODE_SERVER_PROD)s/rs_ts
exec_ck_url = http://%(SPIDER_NODE_SERVER_PROD)s/rs_cookie

[DINGTALK]
crawl_error_token = https://oapi.dingtalk.com/robot/send?access_token=8ca34b6ddaa5d96cd2eb16ccf34ff1a4f7234269c7536b4a04bbaf841eb05e98
insert_data_token = https://oapi.dingtalk.com/robot/send?access_token=8e7184dd301ae1066ee0eea7d2b0dd750c61bf9c48facf313b0b30a5091407c1

[MINIO]
endpoint = %(SPIDER_OSS_ENDPOINT_PROD)s
access_key = %(SPIDER_MINIO_ACCESS_PROD)s
secret_key = %(SPIDER_MINIO_SECRET_PROD)s
secure = false
region = cn-wdy-1
bucket_name = pdffile

[ADMIN]
api_url = http://10.88.0.1:5000
api_token = dev_token
